language: node_js # 构建所需的语言环境
node_js:
  - "v11.14.0"  # 对应的版本
branches:
  only:
  - master    # 构建的分支
#cache:
  #directories:
  #- node_modules # 依赖缓存的目录
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
 - npm install -g gitbook-cli # 安装编译工具
script:
#想用自己自定义的插件时，把自己的node_moduls上传到github,部署时不用再次gitbook install
#或者保留自己的插件到node_moduls里，其他插件利用mpm install gitbook-pluins-包 安装
# - gitbook install 
- gitbook build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN # github 上的token环境变量
  local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master